### ISSUE TITLE
Test suite fails to run when using create-react-app

### ISSUE THREAD

**Issue by jaagupku** [terrestris/react-geo#1283]
React app is created with `create-react-app`

```
package.json

{
  "name": "application",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@nieuwlandgeo/sldreader": "^0.2.1",
    "@terrestris/react-geo": "^12.1.0",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^8.0.3",
    "antd": "^3.26.7",
    "axios": "^0.19.1",
    "core-js": "^3.6.4",
    "ol": "^6.1.1",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-hanger": "^2.1.3",
    "react-scripts": "3.3.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.2",
    "react-app-rewired": "^2.1.5"
  }
}
```

The component
```
// TestComponent.jsx

import React from 'react';
import { Legend } from '@terrestris/react-geo';

export default function TestComponent(props) {
  return (
          <Legend layer={props.layer} />
  );
}
```

The test
```
// TestComponent.spec.jsx

import React from 'react';
import { shallow } from 'enzyme';
import TestComponentfrom './TestComponent';

describe('TestComponent', () => {
  let component = null;

  beforeEach(() => {
    component = shallow(<TestComponentlayers={[]} />);
  });

  it('Should render without errors', () => {
    expect(component).toBeDefined();
  });
});
```

Tests are run with `npm test`

Expected result: Tests pass

Actual result:
```
 FAIL  src/components/LegendList/LegendList.test.jsx
  ● Test suite failed to run

    C:\workspaces\KEMIT\veebikaart\node_modules\antd\es\checkbox\style\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import '../../style/index.less';

                           ^^^^^^^^^^^^^^^^^^^^^^^^

    SyntaxError: Unexpected string

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (node_modules/@terrestris/react-geo/dist/Container/AddWmsPanel/AddWmsPanel.js:8:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        8.103s
Ran all test suites.

Watch Usage: Press w to show more.
```

**Comment by dnlkoch** [comment]
Jest ignores all `node_modules` by default for transformation. To overcome this for untranspiled modules (like `antd`) you might need to whitelist these modules by adding the following config to your `package.json`:

```
"jest": {
  "transformIgnorePatterns": [
    "/node_modules/(?!(ol|css-animation|antd|@terrestris|(rc-*[a-z]*))/).*/"
  ]
}
```

See [here](https://create-react-app.dev/docs/running-tests/#configuration) and [here](https://jestjs.io/docs/en/configuration.html#transformignorepatterns-arraystring) for more details.

**Comment by jaagupku** [comment]
Okay, thanks got it working.
In addition i had to add
```
"moduleNameMapper": {
  "\\.(css|less)$": "<rootDir>/jest/__mocks__/styleMock.js"
}
```

```
// styleMock.js

module.exports = {};
```

And finally in `setupTests.js` import `jest-canvas-mock`
```
import 'jest-canvas-mock';
...
```
